# Generated by Django 3.2 on 2023-08-25 08:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=255, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=None, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 8, 25))])),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=32)),
            ],
        ),
    ]
