# Generated by Django 3.2 on 2023-08-27 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=None, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 8, 27))]),
        ),
    ]
