# Generated by Django 3.2 on 2023-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='short_descr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
