# Generated by Django 3.2 on 2023-08-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_alter_note_noteowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteowner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allNote', to=settings.AUTH_USER_MODEL),
        ),
    ]
